sudo: false
language: node_js
before_install:
- gem install sass compass
node_js:
- iojs
before_script:
- npm install -g bower grunt-cli
- bower install
script:
- grunt build
- bash ./publish.sh
env:
  global:
  - GIT_NAME: Travis-CI
  - GIT_EMAIL: travis.ci.build@gmail.com
  - GH_REF: github.com/parkattack/parkattack.github.io.git
  - GH_PAGES_BRANCH: master
  - secure: B3dy6FHfB10RLg2FLa7SX836ybh88KRfUAe40Pj2wtWxFmu45kx1/Z0ePAoTHOsaKGFa9EUl9mFqwL4ERR0jCeFtJLYUtRyC2eHFS9MZqA1YLct5pSZjfx3cxCSOHZHa6FVgK0F9ipA5hYNd1DoFpcPGh7U42+zjWdAccTbLg4cDAjVQkHK34jhkRiZyxrzMOF0c5IOCYJlbKxlPzGm7zuNpVLpNxPvO8Ng1QYhLJxWcXVsfsESDZ4NEqZR12Sf5qlFF29INgWh8UmC0J6qGMg0cBDjJ5JaXyjktVY/f2Hfxm5Ap66Xi8/DqNi8MiiQfDBTWE3+heNkQW+CWwWyYxc2BA6ExBQbInPnEmyDq3cg9kt4iQVpkEFtCnoozWtmLQblCuKwpI3YkrM4i9bBs80KxWGRNRv9Pls2LVZKlIBjJpSqbxMZBC9ehY0p+XZ6ZZ3cFZrli2P4A7DwfeXe9BSPmXuY1tysPkefT+NpP7iiM9iLuewAadQTosMyJzxNNqTiVgeWXRTIMXXymtDLnVfUfTAMSqTLC6B5AZh+dPgv4rremb2t2M22RcQt9qJHmsJGbN7EmYATujZyTJP4hHVhYbeZ/rPC/vE1OeDI2WCGVcfH5VGRDDamULb2udsvL20elVDev4gcVE698HhYeRTVBjXNA3bOwLx14mLwOgGY=
